spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/asker_lve?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true
    username: root
    password:
    hikari:
      maximum-pool-size: 5
      max-lifetime: 480000
      idle-timeout: 360000

logging:
  level:
    com.askerlve.query.demo.mapper: debug